# Site settings
# baseURL = "https://bszutorportfolio.netlify.app"
languageCode = "en-us"
title = "Portfolio website for Szutor Balint"
theme = "forty"

# Enter your tracking code to enable Google Analytics
googleAnalytics = ""

# Enter your disqus shortname to enable comments
disqusShortname = ""

[params]
  # You can use Markdown syntax for urls [text](//url.to/source)
  # To create multi-line text in strings use the """example Text""" format
  #
  # All icons using Fontawesome's icon font. Look at fontawesome.io/icons
  # for more icons. The icons are represented by their corresponding
  # CSS class.

  # Provide your metadata here.
  name = "Balint Szutor"
  description = "On this webpage I will try to showcase the works I am most proud of. Please enjoy, and if you have any advice feel free to reach out to me at bszutor.mfa2021@london.edu"

  # Link custom assets relative to /static
  custom_css = []
  custom_js  = []
  favicon    = "favicon.ico"

  # Just a custom image variable, please define it in .md files for content.
  image = ""

  # 404 error customization
  [params.error404]
    heading = "Page couldn't be found, sorry"
    text = "Please visit [this page](/)"

  # Navigation Section
  [params.navigation]
    title = "Balint"
    subtitle = "My portfolio"
    menu = "Menu"
    # Optional logo as brand stored in img/
    # logo = "logo.png"

    [[params.navigation.links]]
      name = "Home"
      url = "#"

    [[params.navigation.links]]
      name = "Network science"
      url = "projects/projects1"

    [[params.navigation.links]]
      name = "German consumption"
      url = "projects/projects2"

    [[params.navigation.links]]
      name = "Moscow districts"
      url = "https://balintszut.shinyapps.io/infograph/?fbclid=IwAR1LPu1asj-Q-1FI-zMY_X-6VD3mjSs01H-L05bGcEEkrIcvw76xpdFZClw"

    [[params.navigation.links]]
      name = "My resumé"
      url = "projects/projects3"


  # Banner section
  [params.banner]
    # To change the background image on the homepage banner, replace 'banner.jpg' in
    # the 'static/img' folder.
    title = "Hi, welcome to my portfolio"
    subtitle = "WELCOME TO MY PORTFOLIO."
    buttonText = "Let's go"


  # Tiles Section
  [params.tiles]
    enable = true
    # Display your showcases here.
    
    [[params.tiles.showcase]]
      title = "Network science"
      subtitle = "Network of restaurants around Deak Ferenc square\nBasic recommendation algorithm"
      image = "network.jpg"
      url = "projects/project1"

    [[params.tiles.showcase]]
      title = "Moscow districs"
      subtitle = "Hungarian inforgraphics about Moscow\nwith models about services there"
      image = "cover.jpg"
      url = "https://balintszut.shinyapps.io/infograph/?fbclid=IwAR1LPu1asj-Q-1FI-zMY_X-6VD3mjSs01H-L05bGcEEkrIcvw76xpdFZClw"

    [[params.tiles.showcase]]
      title = "Modelling German consumption"
      subtitle = "Time series analysis of the german economy's consumption\nWith data cleaning and prediction (MICE)"
      image = "germany.jpg"
      url = "projects/project2"

    [[params.tiles.showcase]]
      title = "My resumé"
      subtitle = "If you would like to learn more about my professional experience\nPlease take a look at my CV"
      image = "cv.jpg"
      url = "projects/project3"

  [params.blog]
    # All blogs defined in their own files. You can find example blogs
    # at 'exampleSite/content/blogs'. Copy the 'blogs' folder into the 'content' directory
    # at the root of this Hugo site.
    # For more informtion take a look at the README.
    # To add more blogs just copy and paste the code.

  # Section Type Two
  [params.two]
    enable = true
    title = "Exciting projects"
    subtitle = """Nullam et orci eu lorem consequat tincidunt vivamus et sagittis libero. 
    Mauris aliquet magna magna sed nunc rhoncus pharetra. 
    Pellentesque condimentum sem. In efficitur ligula tate urna. Maecenas laoreet massa vel lacinia pellentesque lorem ipsum dolor. 
    Nullam et orci eu lorem consequat tincidunt. Vivamus et sagittis libero.
    Mauris aliquet magna magna sed nunc rhoncus amet pharetra et feugiat tempus."""
    buttonText = "Get Started"
    url = "blogs"


  # Contact section
  [params.contact]
    enable = true
    buttonSend = "Send message"
    buttonClear = "Clear"

    # Since this template is static, the contact form uses www.formspree.io as a
    # proxy. The form makes a POST request to their servers to send the actual
    # email. Visitors can send up to a 1000 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - set your email address under 'email' below and uncomment
    # - upload the generated site to your server
    # - send a dummy email yourself to confirm your account
    # - click the confirm link in the email from www.formspree.io
    # - you're done. Happy mailing!
    # formEmail = "example@domain.com"

    # Contact Section
    # You can add multiple emails, phone numbers, or addresses
    # by copying the corresponding map with frontmatter code.
    [[params.contact.email]]
    title = "Email"
    email = "example@domain.com"

    [[params.contact.phone]]
    title = "Phone"
    phone = "Ring ring number"

  # Footer section
  [params.footer]
    enable = true
    copyright = "Balint Inc."

    # Uses font awesome icons
    [[params.footer.social]]
      icon = "fa-twitter"
      url= "https://www.twitter.com"
      label = "Twitter"

    [[params.footer.social]]
      icon = "fa-facebook"
      url= "https://www.facebook.com"
      label = "Facebook"

    [[params.footer.social]]
      icon = "fa-instagram"
      url= "https://www.instagram.com"
      label = "Instagram"
    
    [[params.footer.social]]
      icon = "fa-github"
      url= "https://www.github.com"
      label = "GitHub"

    [[params.footer.social]]
      icon = "fa-linkedin"
      url= "https://www.linkedin.com"
      label = "LinkedIn"

    [[params.footer.quicklinks]]
      text = "Design: "
      url= "https://www.html5up.net"
      alt = "HTML5 UP"
