---
title: "Varos Ingatlan infograph"
author: "Balint Szutor and Balint Nyakas"
date: '2020 március 29 '
output: html_document
runtime: shiny
slug: blog5
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(ggmap)
library(rjson)
library(broom)
library(data.table)
library(geojsonio)
library(plotly)
library(shiny)

ingatlan_data <- fread("data/clean_ingatlan_nm.csv", na.strings = c("NA"), dec=",")

var_dict <- fread("data/data_dict.csv")

merged_map <- geojson_read("districts/merged/MoscowDistricts2.geojson",  what = "sp")

merged_map_fortified <- tidy(merged_map, region = "name", .name_repair = c("minimal"))

merged_map_fortified$group <- gsub(" District", "", merged_map_fortified$group)
merged_map_fortified$group <- gsub(".1", "", merged_map_fortified$group)

get_ingatlan_data <- function(var_name){
  b <- ingatlan_data[, mean(eval(parse(text = var_name))), by = sub_area]
  return(merge(merged_map_fortified, b, by.x= "group", by.y= "sub_area", all.x = T)$V1)
}
```

# Több ábra

Itt található a dashboard amivel el lehet készíteni további ábrákat, amikre mi már nem gondoltunk. Szellemes szövegek helyett, azonban csak a standard leírásai lesznek a változóknak, ezért szíves elnézését kérjük az olvasónak.

```{r, echo=FALSE}
ui <- fluidPage(
  titlePanel(title=h4("Moscow districts", align="center")),
  sidebarPanel( 
    selectInput("var_nm", "Válassz változót", colnames(ingatlan_data), selected = "full_sq"),
    textOutput("selected_var")),
  mainPanel(plotOutput("plot2")))

server <- function(input,output){
  
  output$selected_var <- renderText({ 
    var_dict$Description[var_dict$Variable == input$var_nm]
  })
  
  dat <- reactive({
    return(get_ingatlan_data(input$var_nm))
  })
  
  output$plot2<-renderPlot({
    
    reac_data <- dat()
    
    merged_map_fortified %>% 
      mutate(highlight_flag = reac_data) %>% 
      ggplot() +
      geom_polygon(aes(x = long, y = lat, group = group, fill = highlight_flag)) +
      theme_void() +
      coord_map() +
      labs(fill = "Skála") +
      scale_fill_gradient(low=rgb(250, 177, 160, maxColorValue = 255), high=rgb(214, 48, 49, maxColorValue = 255))})
  }
  
shinyApp(ui, server)
```


